In [ ]:
import pandas as pd
import re
import nltk
import time
import numpy as np

# nltk.download('punkt_tab')
# nltk.download('stopwords', quiet=True)
# nltk.download('wordnet', quiet=True)

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, LSTM, Input
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Model

In [ ]:
data = pd.read_csv("arabic_english_dataset.csv")
data.head(3)

        english      arabic
0         hello       مرحبا
1  good morning  صباح الخير
2  good evening  مساء الخير

In [ ]:
data["arabic"] = ("<start> " + data["arabic"].astype(str) + " <end>")
data["arabic"].head()

0         <start> مرحبا <end>
1    <start> صباح الخير <end>
2    <start> مساء الخير <end>
3      <start> كيف حالك <end>
4      <start> أنا بخير <end>
Name: arabic, dtype: object

In [ ]:
arb_tokenizer = Tokenizer(filters="")
arb_tokenizer.fit_on_texts(data["arabic"])

arb_sequences = arb_tokenizer.texts_to_sequences(data["arabic"])

arb_vocab_size = len(arb_tokenizer.word_index) + 1

In [ ]:
eng_tokenizer = Tokenizer(filters="")
eng_tokenizer.fit_on_texts(data["english"])

eng_sequences = eng_tokenizer.texts_to_sequences(data["english"])

eng_vocab_size = len(eng_tokenizer.word_index) + 1

In [ ]:
max_eng_len = max(len(seq) for seq in eng_sequences)
max_arb_len = max(len(seq) for seq in arb_sequences)

print("English max length:", max_eng_len)
print("Arabic max length:", max_arb_len)

English max length: 4
Arabic max length: 6

In [ ]:
encoder_input = pad_sequences(
    eng_sequences,
    maxlen=max_eng_len,
    padding="post"
)

decoder_input = pad_sequences(
    [seq[:-1] for seq in arb_sequences],
    maxlen=max_arb_len - 1,
    padding="post"
)

decoder_target = pad_sequences(
    [seq[1:] for seq in arb_sequences],
    maxlen=max_arb_len - 1,
    padding="post"
)

decoder_target = np.expand_dims(decoder_target, -1)

In [ ]:
latent_dim = 256

encoder_inputs = Input(shape=(max_eng_len,))

encoder_embedding = Embedding(
    input_dim=eng_vocab_size,
    output_dim=256,
    mask_zero=True
)(encoder_inputs)

_, state_h, state_c = LSTM(
    latent_dim,
    return_state=True,
    dropout=0.3,
    recurrent_dropout=0.3
)(encoder_embedding)

encoder_states = [state_h, state_c]

In [ ]:

decoder_inputs = Input(shape=(max_arb_len - 1,))

decoder_embedding = Embedding(
    input_dim=arb_vocab_size,
    output_dim=256,
    mask_zero=True
)(decoder_inputs)

decoder_lstm = LSTM(
    latent_dim,
    return_sequences=True,
    return_state=True,
    dropout=0.3,
    recurrent_dropout=0.3
)

decoder_outputs, _, _ = decoder_lstm(
    decoder_embedding,
    initial_state=encoder_states
)

decoder_dense = Dense(
    arb_vocab_size,
    activation="softmax"
)

decoder_outputs = decoder_dense(decoder_outputs)

In [ ]:
model = Model(
    [encoder_inputs, decoder_inputs],
    decoder_outputs
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_12      │ (None, 4)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_13      │ (None, 5)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_12        │ (None, 4, 256)    │     20,736 │ input_layer_12[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_4         │ (None, 4)         │          0 │ input_layer_12[0… │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_13        │ (None, 5, 256)    │     20,224 │ input_layer_13[0… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_12 (LSTM)      │ [(None, 256),     │    525,312 │ embedding_12[0][… │
│                     │ (None, 256),      │            │ not_equal_4[0][0] │
│                     │ (None, 256)]      │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_13 (LSTM)      │ [(None, 5, 256),  │    525,312 │ embedding_13[0][… │
│                     │ (None, 256),      │            │ lstm_12[0][1],    │
│                     │ (None, 256)]      │            │ lstm_12[0][2]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 5, 79)     │     20,303 │ lstm_13[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,111,887 (4.24 MB)

 Trainable params: 1,111,887 (4.24 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(
    [encoder_input, decoder_input],
    decoder_target,
    validation_split=0.2,
    epochs=100,
    batch_size=64
)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.0091 - loss: 4.3662 - val_accuracy: 0.2800 - val_loss: 4.3616
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.2909 - loss: 4.3485 - val_accuracy: 0.3200 - val_loss: 4.3514
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.3000 - loss: 4.3283 - val_accuracy: 0.3200 - val_loss: 4.3392
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.2909 - loss: 4.3065 - val_accuracy: 0.3200 - val_loss: 4.3241
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.2909 - loss: 4.2796 - val_accuracy: 0.3200 - val_loss: 4.3045
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.2909 - loss: 4.2428 - val_accuracy: 0.3200 - val_loss: 4.2787
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.2909 - loss: 4.2027 - val_accuracy: 0.3200 - val_loss: 4.2445
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.2909 - loss: 4.1435 - val_accuracy: 0.3200 - val_loss: 4.1988
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.2909 - loss: 4.0660 - val_accuracy: 0.3200 - val_loss: 4.1376
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.2909 - loss: 3.9591 - val_accuracy: 0.3200 - val_loss: 4.0557
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.2909 - loss: 3.8233 - val_accuracy: 0.3200 - val_loss: 3.9466
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.2909 - loss: 3.6317 - val_accuracy: 0.3200 - val_loss: 3.8034
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - accuracy: 0.2909 - loss: 3.4633 - val_accuracy: 0.3200 - val_loss: 3.6324
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - accuracy: 0.2909 - loss: 3.4019 - val_accuracy: 0.3200 - val_loss: 3.5039
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.2909 - loss: 3.4079 - val_accuracy: 0.3200 - val_loss: 3.4641
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step - accuracy: 0.2909 - loss: 3.4943 - val_accuracy: 0.3200 - val_loss: 3.4778
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step - accuracy: 0.2909 - loss: 3.4171 - val_accuracy: 0.3200 - val_loss: 3.5173
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - accuracy: 0.2909 - loss: 3.3269 - val_accuracy: 0.3200 - val_loss: 3.5739
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step - accuracy: 0.2909 - loss: 3.2554 - val_accuracy: 0.3200 - val_loss: 3.6407
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.2909 - loss: 3.2004 - val_accuracy: 0.3200 - val_loss: 3.7069
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.3545 - loss: 3.1708 - val_accuracy: 0.3200 - val_loss: 3.7617
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.3545 - loss: 3.1669 - val_accuracy: 0.3200 - val_loss: 3.8020
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.3545 - loss: 3.1593 - val_accuracy: 0.3200 - val_loss: 3.8262
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.3545 - loss: 3.1563 - val_accuracy: 0.3200 - val_loss: 3.8369
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.3545 - loss: 3.1300 - val_accuracy: 0.3200 - val_loss: 3.8373
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.3545 - loss: 3.0844 - val_accuracy: 0.3200 - val_loss: 3.8318
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.3545 - loss: 3.0451 - val_accuracy: 0.3200 - val_loss: 3.8251
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.3545 - loss: 3.0014 - val_accuracy: 0.3200 - val_loss: 3.8230
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.3545 - loss: 2.9738 - val_accuracy: 0.3200 - val_loss: 3.8288
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.3545 - loss: 2.9331 - val_accuracy: 0.3200 - val_loss: 3.8435
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.3545 - loss: 2.9093 - val_accuracy: 0.3200 - val_loss: 3.8646
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.3545 - loss: 2.8933 - val_accuracy: 0.3200 - val_loss: 3.8890
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.3545 - loss: 2.8529 - val_accuracy: 0.3200 - val_loss: 3.9138
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.3545 - loss: 2.7990 - val_accuracy: 0.3200 - val_loss: 3.9378
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.3545 - loss: 2.7559 - val_accuracy: 0.3200 - val_loss: 3.9614
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.3545 - loss: 2.7246 - val_accuracy: 0.3200 - val_loss: 3.9846
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.3545 - loss: 2.6748 - val_accuracy: 0.3200 - val_loss: 4.0065
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.3455 - loss: 2.6499 - val_accuracy: 0.3200 - val_loss: 4.0261
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.3545 - loss: 2.5942 - val_accuracy: 0.3200 - val_loss: 4.0439
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.3545 - loss: 2.5405 - val_accuracy: 0.3200 - val_loss: 4.0609
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.3545 - loss: 2.4993 - val_accuracy: 0.3200 - val_loss: 4.0784
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.3545 - loss: 2.4528 - val_accuracy: 0.3200 - val_loss: 4.0979
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.3545 - loss: 2.4235 - val_accuracy: 0.3200 - val_loss: 4.1202
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.3545 - loss: 2.3557 - val_accuracy: 0.3200 - val_loss: 4.1446
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.3636 - loss: 2.3210 - val_accuracy: 0.3200 - val_loss: 4.1717
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.3727 - loss: 2.2931 - val_accuracy: 0.3200 - val_loss: 4.2005
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.4091 - loss: 2.2235 - val_accuracy: 0.3200 - val_loss: 4.2305
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.4273 - loss: 2.1958 - val_accuracy: 0.3200 - val_loss: 4.2624
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.4273 - loss: 2.1402 - val_accuracy: 0.3200 - val_loss: 4.2979
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.4364 - loss: 2.0917 - val_accuracy: 0.3200 - val_loss: 4.3366
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.4364 - loss: 2.0450 - val_accuracy: 0.3200 - val_loss: 4.3789
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.4182 - loss: 1.9995 - val_accuracy: 0.3200 - val_loss: 4.4198
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.4545 - loss: 1.9409 - val_accuracy: 0.3200 - val_loss: 4.4585
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.5000 - loss: 1.8766 - val_accuracy: 0.3200 - val_loss: 4.4976
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.4636 - loss: 1.8139 - val_accuracy: 0.3200 - val_loss: 4.5363
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.5182 - loss: 1.7436 - val_accuracy: 0.3200 - val_loss: 4.5808
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.4818 - loss: 1.7035 - val_accuracy: 0.3200 - val_loss: 4.6272
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.5545 - loss: 1.6504 - val_accuracy: 0.3200 - val_loss: 4.6848
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.6182 - loss: 1.5729 - val_accuracy: 0.3200 - val_loss: 4.7583
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.6091 - loss: 1.4974 - val_accuracy: 0.3200 - val_loss: 4.8397
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.6000 - loss: 1.4478 - val_accuracy: 0.3200 - val_loss: 4.9220
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.6545 - loss: 1.3673 - val_accuracy: 0.3200 - val_loss: 5.0113
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.7091 - loss: 1.3327 - val_accuracy: 0.3200 - val_loss: 5.1130
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.7091 - loss: 1.2774 - val_accuracy: 0.3200 - val_loss: 5.2229
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7273 - loss: 1.1901 - val_accuracy: 0.3200 - val_loss: 5.3297
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.7273 - loss: 1.1118 - val_accuracy: 0.3200 - val_loss: 5.4301
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.8091 - loss: 1.0718 - val_accuracy: 0.3200 - val_loss: 5.5177
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 0.8182 - loss: 0.9927 - val_accuracy: 0.3200 - val_loss: 5.6036
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.8818 - loss: 0.9556 - val_accuracy: 0.3600 - val_loss: 5.7045
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.8818 - loss: 0.8882 - val_accuracy: 0.3600 - val_loss: 5.8080
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.8727 - loss: 0.8621 - val_accuracy: 0.3600 - val_loss: 5.9249
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.8636 - loss: 0.8023 - val_accuracy: 0.3600 - val_loss: 6.0343
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.9091 - loss: 0.7573 - val_accuracy: 0.3600 - val_loss: 6.1368
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.9182 - loss: 0.7222 - val_accuracy: 0.3600 - val_loss: 6.2372
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.9273 - loss: 0.6523 - val_accuracy: 0.3600 - val_loss: 6.3292
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.9455 - loss: 0.6065 - val_accuracy: 0.3600 - val_loss: 6.4234
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.9273 - loss: 0.6059 - val_accuracy: 0.3600 - val_loss: 6.5247
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.9182 - loss: 0.5694 - val_accuracy: 0.3600 - val_loss: 6.6234
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9727 - loss: 0.5000 - val_accuracy: 0.3600 - val_loss: 6.7238
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9636 - loss: 0.4984 - val_accuracy: 0.3600 - val_loss: 6.7988
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9636 - loss: 0.4606 - val_accuracy: 0.3600 - val_loss: 6.8808
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.9727 - loss: 0.4625 - val_accuracy: 0.3600 - val_loss: 6.9290
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.9909 - loss: 0.4103 - val_accuracy: 0.3600 - val_loss: 6.9670
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 1.0000 - loss: 0.3869 - val_accuracy: 0.3600 - val_loss: 7.0007
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.9818 - loss: 0.3527 - val_accuracy: 0.3600 - val_loss: 7.0386
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.9727 - loss: 0.3454 - val_accuracy: 0.3600 - val_loss: 7.0976
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.9727 - loss: 0.3295 - val_accuracy: 0.3600 - val_loss: 7.1581
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.9909 - loss: 0.3145 - val_accuracy: 0.3600 - val_loss: 7.2327
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.9818 - loss: 0.3029 - val_accuracy: 0.3600 - val_loss: 7.3179
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.9818 - loss: 0.2796 - val_accuracy: 0.3600 - val_loss: 7.3800
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.9909 - loss: 0.2595 - val_accuracy: 0.3600 - val_loss: 7.4430
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.9818 - loss: 0.2632 - val_accuracy: 0.3600 - val_loss: 7.4865
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.9818 - loss: 0.2553 - val_accuracy: 0.3600 - val_loss: 7.5023
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - accuracy: 0.9818 - loss: 0.2305 - val_accuracy: 0.3600 - val_loss: 7.4982
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step - accuracy: 0.9818 - loss: 0.2064 - val_accuracy: 0.3600 - val_loss: 7.5025
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - accuracy: 0.9818 - loss: 0.2140 - val_accuracy: 0.3600 - val_loss: 7.5256
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step - accuracy: 0.9818 - loss: 0.2140 - val_accuracy: 0.3600 - val_loss: 7.5685
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step - accuracy: 1.0000 - loss: 0.1817 - val_accuracy: 0.3600 - val_loss: 7.6060
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 1.0000 - loss: 0.1665 - val_accuracy: 0.3600 - val_loss: 7.6492
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.9818 - loss: 0.1786 - val_accuracy: 0.3600 - val_loss: 7.6997

In [ ]:
print("Training Accuracy:", history.history["accuracy"][-1]*100)
print("Validation Accuracy:", history.history["val_accuracy"][-1]*100)

Training Accuracy: 98.181813955307
Validation Accuracy: 35.999998450279236

In [ ]:
loss, accuracy = model.evaluate(
    [encoder_input, decoder_input],
    decoder_target,
    verbose=0
)

print("Accuracy:", accuracy*100)
print("Loss:", loss)

Accuracy: 88.14814686775208
Loss: 1.6478641033172607